package entities;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "Account", catalog = "mydemo")
public class Account implements java.io.Serializable {
	 private static final long serialVersionUID = 1L;
	 private String username;
	 private Role role;
	 private String password;
	 private String fullName;
	 private String email;
	 private String website;
	 private Set<Orders> orderses = new HashSet<Orders>(0);

	 public Account() {
	 }

	 public Account(String username, Role role, String password) {
		  this.username = username;
		  this.role = role;
		  this.password = password;
	 }

	 public Account(String username, Role role, String password, String fullName, String email, String website,
				Set<Orders> orderses) {
		  this.username = username;
		  this.role = role;
		  this.password = password;
		  this.fullName = fullName;
		  this.email = email;
		  this.website = website;
		  this.orderses = orderses;
	 }

	 @Id
	 @Column(name = "username", unique = true, nullable = false, length = 50)
	 public String getUsername() {
		  return this.username;
	 }

	 public void setUsername(String username) {
		  this.username = username;
	 }

	 @ManyToOne(fetch = FetchType.LAZY)
	 @JoinColumn(name = "roleId", nullable = false)
	 public Role getRole() {
		  return this.role;
	 }

	 public void setRole(Role role) {
		  this.role = role;
	 }

	 @Column(name = "password", nullable = false, length = 250)
	 public String getPassword() {
		  return this.password;
	 }

	 public void setPassword(String password) {
		  this.password = password;
	 }

	 @Column(name = "fullName", length = 50)
	 public String getFullName() {
		  return this.fullName;
	 }

	 public void setFullName(String fullName) {
		  this.fullName = fullName;
	 }

	 @Column(name = "email", length = 250)
	 public String getEmail() {
		  return this.email;
	 }

	 public void setEmail(String email) {
		  this.email = email;
	 }

	 @Column(name = "website", length = 250)
	 public String getWebsite() {
		  return this.website;
	 }

	 public void setWebsite(String website) {
		  this.website = website;
	 }

	 @OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	 public Set<Orders> getOrderses() {
		  return this.orderses;
	 }

	 public void setOrderses(Set<Orders> orderses) {
		  this.orderses = orderses;
	 }

}
